dist: trusty
sudo: false

language: scala
scala:
  - 2.10.6
jdk:
  - oraclejdk8
before_script:
  - sudo apt-get install openssl
  - sudo apt-get install libapr1 libapr1-dev
  - ./.travis/nsq/start_nsq.sh ./.travis/nsq
script:
  - sbt test
before_deploy:
  - pip install --user release-manager==0.2.0
deploy:
  skip_cleanup: true
  provider: script
  script: release-manager --config ./.travis/release.yml --check-version --make-artifact --upload-artifact
  on:
    tags: true
